import type { Metadata } from "next";
import { BannerPlacement, ContentStatus } from "@prisma/client";
import { requirePermission } from "@/lib/auth/permissions";
import { db } from "@/lib/db";
import { archiveBanner, createBanner } from "./actions";

export const metadata: Metadata = { title: "Banners | Admin" };
const input = "w-full rounded-2xl border border-vijaya-red/20 bg-white px-4 py-3 text-sm focus-visible:outline focus-visible:outline-2 focus-visible:outline-vijaya-red";

export default async function BannersPage() {
  await requirePermission("content:write");
  const banners = await db.banner.findMany({ orderBy: [{ pinned: "desc" }, { sortOrder: "asc" }, { createdAt: "desc" }] });
  return <section className="space-y-6"><div><p className="text-xs font-extrabold uppercase tracking-[0.18em] text-vijaya-gold">Campaigns</p><h1 className="font-display text-4xl font-bold text-vijaya-red">Banners</h1><p className="text-sm text-vijaya-muted">Structured campaigns for hero, promo, preorder, product-top, and global notice placements.</p></div><form action={createBanner} className="rounded-4xl bg-white p-6 shadow-soft"><h2 className="font-display text-2xl font-bold text-vijaya-red">Create Banner</h2><div className="mt-4 grid gap-4 md:grid-cols-3"><input name="title" required placeholder="Title" className={input} /><input name="subtitle" placeholder="Subtitle" className={input} /><input name="imagePath" placeholder="/assets or https:// image" className={input} /><input name="ctaLabel" placeholder="CTA label" className={input} /><input name="ctaUrl" placeholder="/products" className={input} /><select name="placement" className={input}>{Object.values(BannerPlacement).map((value) => <option key={value} value={value}>{value}</option>)}</select><select name="status" defaultValue={ContentStatus.DRAFT} className={input}>{Object.values(ContentStatus).map((value) => <option key={value} value={value}>{value}</option>)}</select><input name="publishAt" type="datetime-local" className={input} /><input name="unpublishAt" type="datetime-local" className={input} /><input name="sortOrder" type="number" defaultValue={0} className={input} /><label className="flex items-center gap-2 rounded-2xl bg-vijaya-offwhite px-4 py-3 text-sm font-bold"><input name="featured" type="checkbox" />Featured</label><label className="flex items-center gap-2 rounded-2xl bg-vijaya-offwhite px-4 py-3 text-sm font-bold"><input name="pinned" type="checkbox" />Pinned</label></div><button className="mt-5 rounded-full bg-vijaya-red px-7 py-3 font-bold text-white">Create</button></form><div className="rounded-4xl bg-white p-4 shadow-soft">{banners.length ? <div className="divide-y divide-vijaya-red/10">{banners.map((banner) => <article key={banner.id} className="flex flex-wrap items-center justify-between gap-3 py-4"><div><p className="font-bold">{banner.title}</p><p className="text-xs text-vijaya-muted">{banner.placement} · {banner.status} · {banner.publishAt?.toLocaleString("en-IN") ?? "No start"}</p></div><form action={archiveBanner}><input type="hidden" name="id" value={banner.id} /><button className="rounded-full bg-vijaya-pink px-4 py-2 text-xs font-bold text-vijaya-red">Archive</button></form></article>)}</div> : <p className="p-8 text-center text-sm text-vijaya-muted">No banners configured.</p>}</div></section>;
}
