"use client";
import Image from "next/image"; import { useEffect, useRef, useState } from "react"; import type { Product } from "@/data/products"; import { useStore } from "./StoreProvider";
export function ProductCard({product}:{product:Product}){const {add,wishlist,toggleWish}=useStore();const [quick,setQuick]=useState(false);const trigger=useRef<HTMLButtonElement>(null);const wished=wishlist.includes(product.id);
 useEffect(()=>{if(!quick)return;const esc=(e:KeyboardEvent)=>{if(e.key==="Escape"){setQuick(false);trigger.current?.focus()}};document.addEventListener("keydown",esc);document.body.classList.add("overflow-hidden");return()=>{document.removeEventListener("keydown",esc);document.body.classList.remove("overflow-hidden")}},[quick]);
 return <><article className="product-card group relative flex flex-col rounded-4xl bg-white p-4 shadow-soft transition-all duration-200 hover:-translate-y-1 hover:shadow-card sm:p-5" data-product-id={product.id}>
  <button className="absolute right-4 top-4 z-10 grid h-9 w-9 place-items-center rounded-full bg-white/90 text-vijaya-muted shadow-soft transition hover:text-vijaya-red" onClick={()=>toggleWish(product.id)} aria-pressed={wished} aria-label={`${wished?"Remove":"Add"} ${product.name} ${wished?"from":"to"} wishlist`}><span aria-hidden>{wished?"♥":"♡"}</span></button>
  <div className="relative mx-auto mb-3 h-40 w-32 sm:h-44 sm:w-36"><div className="h-full w-full overflow-hidden rounded-3xl bg-vijaya-pink p-2 ring-4 ring-vijaya-offwhite"><Image src={product.image} alt={`Vijaya ${product.name} pack`} fill sizes="144px" className="object-contain" unoptimized/></div><button ref={trigger} onClick={()=>setQuick(true)} className="absolute inset-x-0 bottom-1 mx-auto w-fit rounded-full bg-vijaya-dark/85 px-3 py-1.5 text-[11px] font-extrabold text-white opacity-0 transition group-hover:opacity-100 focus:opacity-100" aria-label={`Quick view ${product.name}`}>◉ Quick View</button></div>
  <span className="mb-2 w-fit rounded-full bg-vijaya-pink px-2.5 py-1 text-[10px] font-extrabold uppercase text-vijaya-red">{product.category==="veg"?"Veg":"Non-Veg"}</span><h3 className="font-display text-base font-bold leading-tight text-vijaya-dark sm:text-lg">{product.name}</h3><p className="mt-1 line-clamp-2 flex-1 text-xs text-vijaya-muted sm:text-sm">{product.description}</p><p className="mt-3 font-display text-sm font-bold text-vijaya-red">Price on request</p><button onClick={()=>add(product.id)} className="mt-3 rounded-full bg-vijaya-red px-4 py-2.5 font-display text-sm font-bold text-white transition hover:bg-vijaya-red2 active:scale-95">Add to Cart</button>
 </article>{quick&&<div className="fixed inset-0 z-[90] flex items-center justify-center bg-vijaya-dark/60 p-4" role="dialog" aria-modal="true" aria-labelledby="quick-title" onMouseDown={e=>{if(e.target===e.currentTarget)setQuick(false)}}><div className="relative grid w-full max-w-2xl gap-6 rounded-4xl bg-white p-6 shadow-2xl sm:grid-cols-2 sm:p-8"><button autoFocus onClick={()=>{setQuick(false);trigger.current?.focus()}} className="absolute right-4 top-4 z-10 grid h-9 w-9 place-items-center rounded-full bg-white shadow-soft" aria-label="Close quick view">×</button><div className="relative min-h-64 rounded-3xl bg-vijaya-pink"><Image src={product.image} alt={`Vijaya ${product.name} pack`} fill className="object-contain p-4" unoptimized/></div><div className="self-center"><span className="text-xs font-bold uppercase text-vijaya-red">{product.category==="veg"?"Veg":"Non-Veg"}</span><h2 id="quick-title" className="mt-2 font-display text-3xl font-bold text-vijaya-dark">{product.name}</h2><p className="mt-3 text-vijaya-muted">{product.description}</p><p className="mt-5 font-display font-bold text-vijaya-red">Price on request</p><button onClick={()=>{add(product.id);setQuick(false)}} className="mt-5 rounded-full bg-vijaya-red px-6 py-3 font-bold text-white">Add to Cart</button></div></div></div>}</>}
