import Link from "next/link";
import { RecipeStatus } from "@prisma/client";
import { ConfirmSubmit } from "@/components/admin/ConfirmSubmit";
import { requirePermission } from "@/lib/auth/permissions";
import { db } from "@/lib/db";
import { archiveRecipe, restoreRecipe } from "./actions";

export default async function Page({ searchParams }: { searchParams: Promise<{ status?: string; q?: string }> }) {
  await requirePermission("recipes:write");
  const params = await searchParams;
  const status = params.status ?? "active";
  const q = params.q?.trim() ?? "";
  const where = { ...(status === "archived" ? { status: RecipeStatus.ARCHIVED } : status === "draft" ? { status: RecipeStatus.DRAFT } : status === "published" ? { status: RecipeStatus.PUBLISHED } : status === "scheduled" ? { status: RecipeStatus.SCHEDULED } : status === "hidden" ? { status: RecipeStatus.HIDDEN } : status === "all" ? {} : { status: { not: RecipeStatus.ARCHIVED } }), ...(q ? { OR: [{ title: { contains: q, mode: "insensitive" as const } }, { slug: { contains: q, mode: "insensitive" as const } }] } : {}) };
  const recipes = await db.recipe.findMany({ where, include: { product: { select: { name: true } } }, orderBy: [{ pinned: "desc" }, { sortOrder: "asc" }, { title: "asc" }] });
  return <section><div className="flex justify-between gap-4"><div><p className="text-xs font-bold uppercase text-vijaya-gold">Recipe CMS</p><h1 className="font-display text-4xl font-bold text-vijaya-red">Recipes</h1></div><Link href="/admin/recipes/new" className="h-fit rounded-full bg-vijaya-red px-6 py-3 font-bold text-white">Create Recipe</Link></div><form className="mt-6 flex flex-col gap-3 rounded-4xl bg-white p-5 sm:flex-row"><input name="q" defaultValue={q} placeholder="Search recipes" className="min-w-0 flex-1 rounded-full border px-5 py-3" /><select name="status" defaultValue={status} className="rounded-full border px-4 py-3"><option value="active">Active</option><option value="published">Published</option><option value="scheduled">Scheduled</option><option value="hidden">Hidden</option><option value="draft">Draft</option><option value="archived">Archived</option><option value="all">All</option></select><button className="rounded-full border-2 border-vijaya-red px-5 font-bold text-vijaya-red">Apply</button></form><div className="mt-6 space-y-3">{recipes.map((recipe) => <article key={recipe.id} className="flex flex-col justify-between gap-4 rounded-4xl bg-white p-5 shadow-soft sm:flex-row"><div><h2 className="font-display text-xl font-bold">{recipe.title}</h2><p className="text-xs text-vijaya-muted">{recipe.slug} · {recipe.status} · {recipe.product?.name ?? "No product"}</p>{recipe.videoUrl && <p className="mt-2 text-xs font-bold text-vijaya-red">Video attached</p>}</div><div className="flex gap-2"><Link href={`/admin/recipes/${recipe.id}`} className="rounded-full border border-vijaya-red px-4 py-2 text-xs font-bold text-vijaya-red">Edit</Link>{recipe.status === RecipeStatus.ARCHIVED ? <form action={restoreRecipe}><input type="hidden" name="id" value={recipe.id} /><button className="rounded-full bg-vijaya-dark px-4 py-2 text-xs font-bold text-white">Restore</button></form> : <form action={archiveRecipe}><input type="hidden" name="id" value={recipe.id} /><ConfirmSubmit message={`Archive ${recipe.title}? This preserves the recipe data.`} className="rounded-full bg-vijaya-pink px-4 py-2 text-xs font-bold text-vijaya-red">Archive</ConfirmSubmit></form>}</div></article>)}{!recipes.length && <p className="rounded-4xl bg-white p-10 text-center text-vijaya-muted">No recipes found.</p>}</div></section>;
}
