/* eslint-disable @next/next/no-img-element */
import type { Metadata } from "next";
import Link from "next/link";
import { Prisma, ProductStatus } from "@prisma/client";
import { db } from "@/lib/db";
import { requirePermission } from "@/lib/auth/permissions";
import { archiveProduct, restoreProduct } from "./actions";
import { ConfirmSubmit } from "@/components/admin/ConfirmSubmit";

export const metadata: Metadata = { title: "Products | Admin" };
const statusOptions = [["active","Active"],["all","All"],["published","Published"],["scheduled","Scheduled"],["hidden","Hidden"],["draft","Draft"],["archived","Archived"]];
function statusWhere(value?: string): Prisma.ProductWhereInput["status"] { if (value === "all") return undefined; if (value === "published") return ProductStatus.PUBLISHED; if (value === "scheduled") return ProductStatus.SCHEDULED; if (value === "hidden") return ProductStatus.HIDDEN; if (value === "draft") return ProductStatus.DRAFT; if (value === "archived") return ProductStatus.ARCHIVED; return { not: ProductStatus.ARCHIVED }; }
function money(value: Prisma.Decimal | null) { return value === null ? "Price on request" : `₹${value.toFixed(2)}`; }

export default async function ProductListPage({ searchParams }: { searchParams: Promise<{ q?: string; status?: string; category?: string; success?: string; error?: string }> }) {
  await requirePermission("products:write");
  const params = await searchParams, q = params.q?.trim() ?? "", status = params.status ?? "active", category = params.category ?? "all";
  const categories = await db.category.findMany({ orderBy: { name: "asc" } });
  const validCategory = categories.find((item) => item.slug === category)?.slug;
  const where: Prisma.ProductWhereInput = { status: statusWhere(status), ...(validCategory ? { category: { slug: validCategory } } : {}), ...(q ? { OR: [{ name: { contains: q, mode: "insensitive" } }, { slug: { contains: q, mode: "insensitive" } }] } : {}) };
  const [products, total, published, drafts, archived] = await Promise.all([
    db.product.findMany({ where, include: { category: true }, orderBy: [{ pinned: "desc" }, { sortOrder: "asc" }, { name: "asc" }] }), db.product.count(), db.product.count({ where: { status: ProductStatus.PUBLISHED } }), db.product.count({ where: { status: ProductStatus.DRAFT } }), db.product.count({ where: { status: ProductStatus.ARCHIVED } }),
  ]);
  const notices: Record<string,string> = { created: "Product created successfully.", updated: "Product updated successfully.", archived: "Product archived.", restored: "Product restored to Draft." };
  return <section><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[0.18em] text-vijaya-gold">Product CMS</p><h1 className="mt-1 font-display text-4xl font-bold text-vijaya-red">Products</h1><p className="mt-1 text-sm text-vijaya-muted">Manage the database catalogue. Published changes synchronize with the storefront.</p></div><Link href="/admin/products/new" className="rounded-full bg-vijaya-red px-6 py-3 text-center font-bold text-white">Create Product</Link></div>
    {params.success && notices[params.success] && <p role="status" className="mt-5 rounded-2xl bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-800">{notices[params.success]}</p>}
    {params.error === "action" && <p role="alert" className="mt-5 rounded-2xl bg-vijaya-pink px-4 py-3 text-sm font-bold text-vijaya-red">The product could not be changed. Please try again.</p>}
    <div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">{[[total,"Total Products"],[published,"Published"],[drafts,"Drafts"],[archived,"Archived"]].map(([count,label]) => <article key={label} className="rounded-3xl bg-white p-4 shadow-soft"><p className="font-display text-3xl font-bold text-vijaya-red">{count}</p><p className="text-xs font-bold text-vijaya-muted">{label}</p></article>)}</div>
    <form method="get" className="mt-6 rounded-4xl bg-white p-5 shadow-soft"><div className="grid gap-4 lg:grid-cols-[1fr_auto_auto]"><div><label htmlFor="product-list-search" className="sr-only">Search products</label><input id="product-list-search" name="q" defaultValue={q} placeholder="Search by product name or slug" className="w-full rounded-full border border-vijaya-red/20 px-5 py-3 text-sm focus-visible:outline focus-visible:outline-2 focus-visible:outline-vijaya-red"/></div><div className="flex flex-wrap gap-2">{statusOptions.map(([value,label]) => <label key={value} className={`cursor-pointer rounded-full px-4 py-2.5 text-xs font-bold ${status === value ? "bg-vijaya-red text-white" : "bg-vijaya-offwhite"}`}><input type="radio" name="status" value={value} defaultChecked={status === value} className="sr-only"/>{label}</label>)}</div><button className="rounded-full border-2 border-vijaya-red px-5 py-2.5 text-sm font-bold text-vijaya-red">Apply</button></div><div className="mt-3 flex flex-wrap gap-2"><label className={`cursor-pointer rounded-full px-4 py-2 text-xs font-bold ${category === "all" ? "bg-vijaya-dark text-white" : "bg-vijaya-offwhite"}`}><input type="radio" name="category" value="all" defaultChecked={category === "all"} className="sr-only"/>All Categories</label>{categories.map((item) => <label key={item.id} className={`cursor-pointer rounded-full px-4 py-2 text-xs font-bold ${category === item.slug ? "bg-vijaya-dark text-white" : "bg-vijaya-offwhite"}`}><input type="radio" name="category" value={item.slug} defaultChecked={category === item.slug} className="sr-only"/>{item.name}</label>)}</div></form>
    <p className="mt-5 text-sm text-vijaya-muted" aria-live="polite">Showing {products.length} product{products.length === 1 ? "" : "s"}</p>
    <div className="mt-3 overflow-hidden rounded-4xl bg-white shadow-soft"><div className="hidden overflow-x-auto md:block"><table className="w-full text-left text-sm"><thead className="bg-vijaya-offwhite text-xs uppercase tracking-wide text-vijaya-muted"><tr><th className="px-5 py-4">Product</th><th className="px-4 py-4">Category</th><th className="px-4 py-4">Price</th><th className="px-4 py-4">Status</th><th className="px-4 py-4">Flags</th><th className="px-4 py-4">Updated</th><th className="px-5 py-4 text-right">Actions</th></tr></thead><tbody className="divide-y divide-vijaya-red/10">{products.map((product) => <tr key={product.id}><td className="px-5 py-4"><div className="flex items-center gap-3"><div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl bg-vijaya-pink p-1"><img src={product.imagePath} alt="" className="h-full w-full object-contain"/></div><div><p className="font-bold text-vijaya-dark">{product.name}</p><p className="text-xs text-vijaya-muted">{product.slug}</p></div></div></td><td className="px-4 py-4">{product.category.name}</td><td className="px-4 py-4 font-bold text-vijaya-red">{money(product.price)}</td><td className="px-4 py-4"><span className="rounded-full bg-vijaya-pink px-2.5 py-1 text-[10px] font-extrabold text-vijaya-red">{product.status}</span></td><td className="px-4 py-4 text-xs">{product.featured && <span className="mr-1">Featured</span>}{product.preorder && <span>Preorder</span>}{!product.featured && !product.preorder && "—"}</td><td className="px-4 py-4 text-xs text-vijaya-muted">{product.updatedAt.toLocaleDateString("en-IN")}</td><td className="px-5 py-4"><div className="flex justify-end gap-2"><Link href={`/admin/products/${product.id}`} className="rounded-full border border-vijaya-red px-3 py-1.5 text-xs font-bold text-vijaya-red">Edit</Link>{product.status === ProductStatus.ARCHIVED ? <form action={restoreProduct}><input type="hidden" name="id" value={product.id}/><button className="rounded-full bg-vijaya-dark px-3 py-1.5 text-xs font-bold text-white">Restore</button></form> : <form action={archiveProduct}><input type="hidden" name="id" value={product.id}/><ConfirmSubmit message={`Archive ${product.name}? This removes it from the active product list but preserves its data.`} className="rounded-full bg-vijaya-pink px-3 py-1.5 text-xs font-bold text-vijaya-red">Archive</ConfirmSubmit></form>}</div></td></tr>)}</tbody></table></div>
      <div className="divide-y divide-vijaya-red/10 md:hidden">{products.map((product) => <article key={product.id} className="p-5"><div className="flex gap-3"><div className="flex h-16 w-16 shrink-0 items-center justify-center rounded-2xl bg-vijaya-pink p-1"><img src={product.imagePath} alt="" className="h-full w-full object-contain"/></div><div className="min-w-0"><h2 className="font-display font-bold">{product.name}</h2><p className="truncate text-xs text-vijaya-muted">{product.slug}</p><p className="mt-1 text-xs font-bold text-vijaya-red">{product.category.name} · {product.status}</p></div></div><div className="mt-4 flex items-center justify-between"><p className="text-sm font-bold text-vijaya-red">{money(product.price)}</p><div className="flex gap-2"><Link href={`/admin/products/${product.id}`} className="rounded-full border border-vijaya-red px-4 py-2 text-xs font-bold text-vijaya-red">Edit</Link>{product.status === ProductStatus.ARCHIVED ? <form action={restoreProduct}><input type="hidden" name="id" value={product.id}/><button className="rounded-full bg-vijaya-dark px-4 py-2 text-xs font-bold text-white">Restore</button></form> : <form action={archiveProduct}><input type="hidden" name="id" value={product.id}/><ConfirmSubmit message={`Archive ${product.name}? This preserves its data.`} className="rounded-full bg-vijaya-pink px-4 py-2 text-xs font-bold text-vijaya-red">Archive</ConfirmSubmit></form>}</div></div></article>)}</div>
      {products.length === 0 && <div className="p-12 text-center text-sm text-vijaya-muted">No products match these filters.</div>}
    </div>
  </section>;
}
