import Link from "next/link";

function Field({ name, label, type = "text", minLength, maxLength, autoComplete }: { name: string; label: string; type?: string; minLength?: number; maxLength?: number; autoComplete?: string }) {
  return <div><label htmlFor={name} className="mb-1.5 block text-sm font-bold">{label}</label><input id={name} name={name} type={type} minLength={minLength} maxLength={maxLength} autoComplete={autoComplete} required className="w-full rounded-2xl border border-vijaya-red/20 bg-white px-4 py-3 focus:outline-vijaya-red" /></div>;
}

export function LoginForm({ error }: { error?: string }) {
  return <form action="/auth/customer/login" method="post" noValidate className="space-y-5">{error && <p role="alert" className="rounded-2xl bg-vijaya-pink px-4 py-3 text-sm font-bold text-vijaya-red">Invalid email or password.</p>}<Field name="email" label="Email address" type="email" maxLength={254} autoComplete="email" /><Field name="password" label="Password" type="password" maxLength={128} autoComplete="current-password" /><div className="flex justify-between text-sm"><label><input name="remember" type="checkbox" className="mr-2" />Remember me</label><span className="font-bold text-vijaya-muted">Password reset unavailable</span></div><button className="w-full rounded-full bg-vijaya-red py-3.5 font-bold text-white">Login</button><p className="text-center text-sm">New here? <Link href="/signup" className="font-bold text-vijaya-red">Create an account</Link></p></form>;
}

export function SignupForm({ error }: { error?: string }) {
  return <form action="/auth/customer/signup" method="post" noValidate className="space-y-4">{error && <p role="alert" className="rounded-2xl bg-vijaya-pink px-4 py-3 text-sm font-bold text-vijaya-red">{error === "exists" ? "An account with this email already exists." : "Please review the submitted account details."}</p>}<Field name="name" label="Full name" minLength={2} maxLength={120} autoComplete="name" /><Field name="email" label="Email address" type="email" maxLength={254} autoComplete="email" /><Field name="mobile" label="Mobile number" type="tel" maxLength={30} autoComplete="tel" /><Field name="password" label="Password" type="password" minLength={8} maxLength={128} autoComplete="new-password" /><Field name="confirm" label="Confirm password" type="password" minLength={8} maxLength={128} autoComplete="new-password" /><label className="block text-sm"><input name="terms" type="checkbox" required className="mr-2" />I accept the Vijaya account terms</label><button className="w-full rounded-full bg-vijaya-red py-3.5 font-bold text-white">Create Account</button><p className="text-center text-sm">Already registered? <Link href="/login" className="font-bold text-vijaya-red">Login</Link></p></form>;
}
