import { requirePermission } from "@/lib/auth/permissions";
import { db } from "@/lib/db";
import { getHomepageSettings } from "@/lib/settings/public";
import { saveHomepage } from "./actions";

const cls = "w-full rounded-2xl border border-vijaya-red/20 px-4 py-3";
const list = (value: unknown) => Array.isArray(value) ? value.filter((item) => typeof item === "string").join("\n") : "";

export default async function Page() {
  await requirePermission("content:write");
  const [homepage, products] = await Promise.all([getHomepageSettings(), db.product.findMany({ where: { status: "PUBLISHED" }, select: { id: true, name: true }, orderBy: { name: "asc" } })]);
  const flags = ["showOffer", "showCategories", "showProducts", "showPromise", "showPackToPlate", "showRecipeVideo", "showReviews", "showPreorder", "showGallery", "showNewsletter"] as const;
  return <section className="max-w-4xl"><h1 className="font-display text-4xl font-bold text-vijaya-red">Homepage</h1><p className="mb-7 text-sm text-vijaya-muted">Manage structured homepage content, section ordering signals, and visibility. No raw HTML or JavaScript editing is allowed.</p><form action={saveHomepage} className="space-y-6"><fieldset className="grid gap-5 rounded-4xl bg-white p-6 shadow-soft sm:grid-cols-2"><legend className="font-display text-xl font-bold text-vijaya-red">Hero</legend>{(["heroEyebrow", "heroHeading", "heroDescription", "heroCtaLabel", "heroCtaUrl"] as const).map((name) => <div key={name}><label htmlFor={name} className="mb-1 block text-sm font-bold">{name.replace("hero", "").replace(/([A-Z])/g, " $1")}</label><input id={name} name={name} defaultValue={homepage[name] ?? ""} className={cls} /></div>)}<div><label htmlFor="heroProductId" className="mb-1 block text-sm font-bold">Featured product</label><select id="heroProductId" name="heroProductId" defaultValue={homepage.heroProductId ?? ""} className={cls}><option value="">Automatic</option>{products.map((product) => <option key={product.id} value={product.id}>{product.name}</option>)}</select></div></fieldset><fieldset className="rounded-4xl bg-white p-6 shadow-soft"><legend className="font-display text-xl font-bold text-vijaya-red">Sections</legend><div className="grid gap-3 sm:grid-cols-2">{flags.map((name) => <label key={name} className="flex items-center gap-3 rounded-2xl bg-vijaya-offwhite p-3"><input type="checkbox" name={name} defaultChecked={Boolean(homepage[name])} />{name.replace("show", "").replace(/([A-Z])/g, " $1")}</label>)}</div></fieldset><fieldset className="grid gap-5 rounded-4xl bg-white p-6 shadow-soft sm:grid-cols-2"><legend className="font-display text-xl font-bold text-vijaya-red">Promise & Pack to Plate</legend><input name="promiseHeading" aria-label="Promise heading" defaultValue={homepage.promiseHeading} className={cls} /><input name="promiseDescription" aria-label="Promise description" defaultValue={homepage.promiseDescription} className={cls} /><textarea name="promiseItems" aria-label="Promise items" rows={6} defaultValue={list(homepage.promiseItems)} placeholder="One promise item per line" className={cls} /><textarea name="packToPlateItems" aria-label="Pack to Plate steps" rows={6} defaultValue={list(homepage.packToPlateItems)} placeholder="One step per line" className={cls} /></fieldset><button className="rounded-full bg-vijaya-red px-7 py-3 font-bold text-white">Save Homepage</button></form></section>;
}
